# Generated by Django 3.0.14 on 2022-03-03 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Отопление')),
            ],
            options={
                'verbose_name': 'Отопление',
                'verbose_name_plural': 'Отопление',
            },
        ),
        migrations.CreateModel(
            name='House_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=50, verbose_name='Материал Дома')),
            ],
            options={
                'verbose_name': 'Материал Дома',
                'verbose_name_plural': 'Материалы Дома',
            },
        ),
        migrations.CreateModel(
            name='Land_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Статус земли')),
            ],
            options={
                'verbose_name': 'Статус земли',
                'verbose_name_plural': 'Статусы земли',
            },
        ),
        migrations.CreateModel(
            name='Post_sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(max_length=1000, verbose_name='Адрес')),
                ('body', models.TextField(max_length=5000, verbose_name='Описание')),
                ('square', models.CharField(blank=True, max_length=4, null=True, verbose_name='Площадь дома')),
                ('floors', models.CharField(blank=True, max_length=2, null=True, verbose_name='Этажей в доме')),
                ('land_area', models.CharField(max_length=7, verbose_name='Площадь участка')),
                ('year_of_construction', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год постройки')),
                ('ceiling_height', models.CharField(blank=True, max_length=5, null=True, verbose_name='Высота потолков')),
                ('price', models.CharField(max_length=30, verbose_name='Цена')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('heating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Heating', verbose_name='Отопление')),
                ('house_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.House_material', verbose_name='Материал Дома')),
                ('land_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Land_status', verbose_name='Статус земли')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Тип сделки')),
                ('slug', models.SlugField(unique=True, verbose_name='URL сделки')),
            ],
            options={
                'verbose_name': 'Тип сделки',
                'verbose_name_plural': 'Типы сделки',
            },
        ),
        migrations.CreateModel(
            name='Type_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=50, verbose_name='Тип объекта')),
                ('slug', models.SlugField(unique=True, verbose_name='URL объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Тип объекта',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=50, verbose_name='Водоснабжение')),
            ],
            options={
                'verbose_name': 'Водоснабжение',
                'verbose_name_plural': 'Водоснабжение',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data_link', models.ImageField(upload_to=posts.models.PostImage.images_directory_path)),
                ('image_url', models.URLField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_images', to='posts.Post_sale')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='post_sale',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Status', verbose_name='Тип сделки'),
        ),
        migrations.AddField(
            model_name='post_sale',
            name='type_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Type_object', verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='post_sale',
            name='water',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Water', verbose_name='Водоснабжение'),
        ),
    ]
