# Generated by Django 3.0.14 on 2022-11-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_sale',
            name='price',
            field=models.IntegerField(max_length=30, verbose_name='Цена'),
        ),
    ]
