# Generated by Django 3.0.14 on 2022-07-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220728_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_sale',
            name='views',
        ),
        migrations.AddField(
            model_name='post_sale',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
