# Generated by Django 3.0.14 on 2022-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220729_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_sale',
            name='type_object',
        ),
        migrations.AddField(
            model_name='post_sale',
            name='type_object',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Type_object', verbose_name='Тип объекта'),
        ),
    ]
