# Generated by Django 3.0.14 on 2023-01-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221108_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Район объекта')),
                ('slug', models.SlugField(unique=True, verbose_name='URL района')),
            ],
            options={
                'verbose_name': 'Район объекта',
                'verbose_name_plural': 'Районы объекта',
            },
        ),
        migrations.AddField(
            model_name='post_sale',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.District', verbose_name='Район'),
        ),
    ]
