# Generated by Django 3.0.14 on 2022-08-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220801_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_sale',
            name='type_object',
            field=models.ManyToManyField(blank=True, to='posts.Type_object', verbose_name='Тип объекта'),
        ),
    ]
