# Generated by Django 3.0.14 on 2023-02-02 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20230131_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottvill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Название поселка')),
                ('slug', models.SlugField(unique=True, verbose_name='URL поселка')),
                ('developer', models.TextField(blank=True, max_length=100, null=True, verbose_name='Застройщик')),
                ('url', models.TextField(blank=True, max_length=100, null=True, verbose_name='Сайт поселка')),
                ('adress', models.TextField(blank=True, max_length=800, null=True, verbose_name='Адрес поселка')),
                ('status_land', models.TextField(blank=True, max_length=100, null=True, verbose_name='Статус земли')),
                ('col_area', models.TextField(blank=True, max_length=4, null=True, verbose_name='Количество участков')),
                ('min_area', models.TextField(blank=True, max_length=6, null=True, verbose_name='Минимальная площадь участка')),
                ('max_area', models.TextField(blank=True, max_length=6, null=True, verbose_name='Максимальная площадь участка')),
                ('price_area', models.TextField(blank=True, max_length=15, null=True, verbose_name='Цена участка')),
                ('сommunications', models.TextField(blank=True, max_length=15, null=True, verbose_name='Коммуникации')),
                ('body', models.TextField(blank=True, max_length=9000, null=True, verbose_name='Описание')),
                ('house_price_min', models.TextField(blank=True, max_length=20, null=True, verbose_name='Минимальная цена дома')),
                ('house_price_max', models.TextField(blank=True, max_length=20, null=True, verbose_name='Максимальная цена дома')),
                ('col_house', models.TextField(blank=True, max_length=4, null=True, verbose_name='Количество домов')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Поселок',
                'verbose_name_plural': 'Поселки',
            },
        ),
    ]
