# Generated by Django 3.0.14 on 2022-08-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220801_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_sale',
            name='type_object',
        ),
        migrations.AddField(
            model_name='post_sale',
            name='type_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Type_object', verbose_name='Тип объекта'),
        ),
    ]
