# Generated by Django 3.0.14 on 2023-02-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230213_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottvill',
            name='slug',
            field=models.SlugField(verbose_name='URL поселка'),
        ),
    ]
