# Generated by Django 3.0.14 on 2022-08-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220801_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=50, verbose_name='Благоустройство')),
                ('slug', models.SlugField(unique=True, verbose_name='URL объекта')),
            ],
            options={
                'verbose_name': 'Благоустройство',
                'verbose_name_plural': 'Благоустройства',
            },
        ),
        migrations.AlterModelOptions(
            name='type_object',
            options={'verbose_name': 'Тип объекта', 'verbose_name_plural': 'Типы объекта'},
        ),
        migrations.AddField(
            model_name='post_sale',
            name='houseAdditional',
            field=models.ManyToManyField(blank=True, to='posts.HouseAdditional', verbose_name='Благоустройство'),
        ),
    ]
