# Generated by Django 3.0.14 on 2023-02-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230213_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottvill',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL поселка'),
        ),
    ]
