# Generated by Django 3.0.14 on 2022-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220801_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=50, verbose_name='Аренда удобства')),
                ('slug', models.SlugField(unique=True, verbose_name='URL объекта')),
            ],
            options={
                'verbose_name': 'Аренда удобства',
                'verbose_name_plural': 'Аренда удобства',
            },
        ),
        migrations.AddField(
            model_name='post_sale',
            name='rent_amenities',
            field=models.ManyToManyField(blank=True, to='posts.Rent_amenities', verbose_name='Аренда удобства'),
        ),
    ]
