# Generated by Django 3.0.14 on 2022-08-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220801_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_sale',
            name='rent_price',
            field=models.CharField(default=12000, max_length=30, verbose_name='Арендная плата'),
            preserve_default=False,
        ),
    ]
