# Generated by Django 3.0.14 on 2023-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230213_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottvill',
            name='title',
            field=models.TextField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='Название поселка'),
        ),
    ]
