# Generated by Django 3.0.14 on 2023-02-15 12:04

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_cottvill_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottvill',
            name='img',
            field=models.ImageField(blank=True, upload_to=posts.models.images_directory_path),
        ),
    ]
