# Generated by Django 3.0.14 on 2023-03-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20230307_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottvill',
            name='col_area',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Количество участков'),
        ),
        migrations.AlterField(
            model_name='cottvill',
            name='max_area',
            field=models.IntegerField(blank=True, max_length=6, null=True, verbose_name='Максимальная площадь участка'),
        ),
        migrations.AlterField(
            model_name='cottvill',
            name='min_area',
            field=models.IntegerField(blank=True, max_length=6, null=True, verbose_name='Минимальная площадь участка'),
        ),
        migrations.AlterField(
            model_name='cottvill',
            name='price_area',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Цена участка'),
        ),
    ]
