# Generated by Django 3.0.14 on 2023-03-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20230309_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottvill',
            name='col_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество участков'),
        ),
        migrations.AlterField(
            model_name='cottvill',
            name='max_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная площадь участка'),
        ),
        migrations.AlterField(
            model_name='cottvill',
            name='min_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальная площадь участка'),
        ),
        migrations.AlterField(
            model_name='cottvill',
            name='price_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена участка'),
        ),
    ]
