# Generated by Django 3.0.14 on 2023-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20230309_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_sale',
            name='adress',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Адрес'),
        ),
    ]
