# Generated by Django 3.0.14 on 2023-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20230313_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottvill',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
