# Generated by Django 3.0.14 on 2023-03-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_cottvill_urgent_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottvill',
            name='urgent_sales',
        ),
    ]
