# Generated by Django 3.0.14 on 2023-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_cottvill_urgent_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_sale',
            name='urgent_sales',
            field=models.BooleanField(default=False, verbose_name='Срочная продажа'),
        ),
    ]
