# Generated by Django 3.0.14 on 2023-03-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_post_sale_urgent_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_sale',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='status_st', to='posts.Status', verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='post_sale',
            name='type_object',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_object_st', to='posts.Type_object', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='type_object',
            name='title',
            field=models.TextField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Тип объекта'),
        ),
    ]
