# Generated by Django 3.0.14 on 2023-03-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20230327_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
