# Generated by Django 3.0.14 on 2023-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_delete_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottvill',
            name='main_slider',
            field=models.BooleanField(default=False, verbose_name='На главном слайдере'),
        ),
    ]
