# Generated by Django 3.0.14 on 2023-03-31 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_cottvill_main_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_sale',
            name='type_object',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='type_object_st', to='posts.Type_object', verbose_name='Тип объекта'),
        ),
    ]
