# Generated by Django 3.0.14 on 2023-04-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20230407_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_sale',
            name='type_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_object_st', to='posts.Type_object', verbose_name='Тип объекта'),
        ),
    ]
