# Generated by Django 3.0.14 on 2023-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20230412_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_sale',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='post_sale',
            name='rent_price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Арендная плата'),
        ),
    ]
