# Generated by Django 3.0.14 on 2023-03-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_rename_indexes'),
    ]

    operations = [
    ]
