# Generated by Django 3.0.14 on 2023-03-31 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_rename_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='Название новости')),
                ('slug', models.SlugField(unique=True, verbose_name='URL новости')),
                ('body', models.TextField(blank=True, max_length=95000, null=True, verbose_name='Текст новости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('views', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, upload_to=news.models.images_directory_path3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
