# Generated by Django 3.0.14 on 2023-03-14 13:53

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constcomp',
            name='img',
            field=models.ImageField(blank=True, upload_to=companies.models.images_directory_path2),
        ),
    ]
