# Generated by Django 3.0.14 on 2023-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20230314_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constcomp',
            name='services',
        ),
        migrations.AddField(
            model_name='constcomp',
            name='services',
            field=models.ManyToManyField(blank=True, to='companies.Services', verbose_name='Услуги'),
        ),
    ]
