# Generated by Django 3.0.14 on 2023-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20230316_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='constcomp',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
