# Generated by Django 3.0.14 on 2023-03-24 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0008_auto_20230324_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], verbose_name='Значение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Адрес')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='companies.Constcomp', verbose_name='Строительная компания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ('-time_create',),
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['-time_create', 'value'], name='companies_r_time_cr_2ee95d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('company', 'ip_address')},
        ),
    ]
