# Generated by Django 3.0.14 on 2023-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20230324_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='constcomp',
            name='rating_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='constcomp',
            name='rating_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
