# Generated by Django 3.0.14 on 2023-03-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20230324_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constcomp',
            name='rating_dislikes',
        ),
        migrations.RemoveField(
            model_name='constcomp',
            name='rating_likes',
        ),
    ]
