# Generated by Django 3.0.14 on 2023-03-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
