# Generated by Django 3.0.14 on 2023-03-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Голоса', 'verbose_name_plural': 'Голоса'},
        ),
    ]
